name: Distribute

on:
  push:
    branches:
    - develop

jobs:
  distribute:
    name: Distribute
    runs-on: ubuntu-latest
    steps:
    - id: clone
      name: "Clone repository"
      uses: actions/checkout@v1
    - id: install
      name: "Install NPM packages"
      run: npm install
    - id: test
      name: "Execute tests"
      env:
        CI: true
      run: npm test
    - id: compile
      name: "Compile TypeScript to JavaScript"
      run: ./node_modules/.bin/tsc
    - id: distribuite
      name: Distribuite
      uses: xeeynamo/action-distribute@develop
      with:
        distribution-branch: 'latest'
        is-typescript: 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
